// Copyright 2026 robj1925. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"skool-pp-cli/internal/cli"
	"skool-pp-cli/internal/client"
	"skool-pp-cli/internal/cliutil"
	"skool-pp-cli/internal/config"
	"skool-pp-cli/internal/mcp/cobratree"
	"skool-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool(".deploy_status_henson.json_list_.deploy_status_henson.json",
			mcplib.WithDescription("GET /v3/.deploy_status_henson.json. Required: canaryPercentage, deployedRevisions. Returns the .deploy_status_henson.json."),
			mcplib.WithNumber("canaryPercentage", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("deployedRevisions", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v3/.deploy_status_henson.json", []mcpParamBinding{{PublicName: "canaryPercentage", WireName: "canaryPercentage", Location: "query"}, {PublicName: "deployedRevisions", WireName: "deployedRevisions", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("017ae153ccc5_create_mp_verify",
			mcplib.WithDescription("POST /017ae153ccc5/4aa4380fa03e/mp_verify. Required: token. Returns the new mp_verify."),
			mcplib.WithString("token", mcplib.Required(), mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/017ae153ccc5/4aa4380fa03e/mp_verify", []mcpParamBinding{{PublicName: "token", WireName: "token", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("017ae153ccc5_create_telemetry",
			mcplib.WithDescription("POST /017ae153ccc5/4aa4380fa03e/telemetry. Required: awswaf_session_storage, next_interval, token. Returns the new telemetry."),
			mcplib.WithString("awswaf_session_storage", mcplib.Required(), mcplib.Description("")),
			mcplib.WithNumber("next_interval", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("token", mcplib.Required(), mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/017ae153ccc5/4aa4380fa03e/telemetry", []mcpParamBinding{{PublicName: "awswaf_session_storage", WireName: "awswaf_session_storage", Location: "query"}, {PublicName: "next_interval", WireName: "next_interval", Location: "query"}, {PublicName: "token", WireName: "token", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("017ae153ccc5_list_inputs",
			mcplib.WithDescription("GET /017ae153ccc5/4aa4380fa03e/inputs. Optional: client. Returns the inputs."),
			mcplib.WithString("client", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/017ae153ccc5/4aa4380fa03e/inputs", []mcpParamBinding{{PublicName: "client", WireName: "client", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("_next_get_about.json",
			mcplib.WithDescription("GET /_next/data/{id}/ai-academy-with-robby-6849/about.json. Required: id. Optional: group. Returns the about.json."),
			mcplib.WithString("group", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id path segment")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/_next/data/{id}/ai-academy-with-robby-6849/about.json", []mcpParamBinding{{PublicName: "group", WireName: "group", Location: "query"}, {PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("_next_get_calendar.json",
			mcplib.WithDescription("GET /_next/data/{id}/ai-academy-with-robby-6849/calendar.json. Required: id. Optional: group. Returns the calendar.json."),
			mcplib.WithString("group", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id path segment")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/_next/data/{id}/ai-academy-with-robby-6849/calendar.json", []mcpParamBinding{{PublicName: "group", WireName: "group", Location: "query"}, {PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("_next_get_classroom.json",
			mcplib.WithDescription("GET /_next/data/{id}/ai-academy-with-robby-6849/classroom.json. Required: id. Optional: group. Returns the classroom.json."),
			mcplib.WithString("group", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id path segment")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/_next/data/{id}/ai-academy-with-robby-6849/classroom.json", []mcpParamBinding{{PublicName: "group", WireName: "group", Location: "query"}, {PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("_next_get_leaderboards.json",
			mcplib.WithDescription("GET /_next/data/{id}/ai-academy-with-robby-6849/-/leaderboards.json. Required: id. Optional: group. Returns the leaderboards.json."),
			mcplib.WithString("group", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id path segment")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/_next/data/{id}/ai-academy-with-robby-6849/-/leaderboards.json", []mcpParamBinding{{PublicName: "group", WireName: "group", Location: "query"}, {PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("_next_get_map.json",
			mcplib.WithDescription("GET /_next/data/{id}/ai-academy-with-robby-6849/-/map.json. Required: id. Optional: group, is. Returns the map.json."),
			mcplib.WithString("group", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id path segment")),
			mcplib.WithNumber("is", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/_next/data/{id}/ai-academy-with-robby-6849/-/map.json", []mcpParamBinding{{PublicName: "group", WireName: "group", Location: "query"}, {PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "is", WireName: "is", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("_next_get_members.json",
			mcplib.WithDescription("GET /_next/data/{id}/ai-academy-with-robby-6849/-/members.json. Required: id. Optional: group, t. Returns the members.json."),
			mcplib.WithString("group", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id path segment")),
			mcplib.WithString("t", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/_next/data/{id}/ai-academy-with-robby-6849/-/members.json", []mcpParamBinding{{PublicName: "group", WireName: "group", Location: "query"}, {PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "t", WireName: "t", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("affiliates_list_compensations",
			mcplib.WithDescription("GET /affiliates/v2/compensations. Optional: cancelled, group_id, limit (plus 2 more). Returns the compensations."),
			mcplib.WithBoolean("cancelled", mcplib.Description("")),
			mcplib.WithString("group_id", mcplib.Description("")),
			mcplib.WithNumber("limit", mcplib.Description("")),
			mcplib.WithNumber("offset", mcplib.Description("")),
			mcplib.WithString("type", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/affiliates/v2/compensations", []mcpParamBinding{{PublicName: "cancelled", WireName: "cancelled", Location: "query"}, {PublicName: "group_id", WireName: "group_id", Location: "query"}, {PublicName: "limit", WireName: "limit", Location: "query"}, {PublicName: "offset", WireName: "offset", Location: "query"}, {PublicName: "type", WireName: "type", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("affiliates_list_payout",
			mcplib.WithDescription("GET /affiliates/payout. Required: code, currency, last_30_days, lifetime, payable, pending, setup_status. Returns the payout."),
			mcplib.WithString("code", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("currency", mcplib.Required(), mcplib.Description("")),
			mcplib.WithNumber("last_30_days", mcplib.Required(), mcplib.Description("")),
			mcplib.WithNumber("lifetime", mcplib.Required(), mcplib.Description("")),
			mcplib.WithNumber("payable", mcplib.Required(), mcplib.Description("")),
			mcplib.WithNumber("pending", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("setup_status", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/affiliates/payout", []mcpParamBinding{{PublicName: "code", WireName: "code", Location: "query"}, {PublicName: "currency", WireName: "currency", Location: "query"}, {PublicName: "last_30_days", WireName: "last_30_days", Location: "query"}, {PublicName: "lifetime", WireName: "lifetime", Location: "query"}, {PublicName: "payable", WireName: "payable", Location: "query"}, {PublicName: "pending", WireName: "pending", Location: "query"}, {PublicName: "setup_status", WireName: "setup_status", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("affiliates_options_compensations",
			mcplib.WithDescription("OPTIONS /affiliates/v2/compensations. Optional: cancelled, group_id, limit (plus 2 more). Returns the compensations."),
			mcplib.WithBoolean("cancelled", mcplib.Description("")),
			mcplib.WithString("group_id", mcplib.Description("")),
			mcplib.WithNumber("limit", mcplib.Description("")),
			mcplib.WithNumber("offset", mcplib.Description("")),
			mcplib.WithString("type", mcplib.Description("")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("OPTIONS", "/affiliates/v2/compensations", []mcpParamBinding{{PublicName: "cancelled", WireName: "cancelled", Location: "query"}, {PublicName: "group_id", WireName: "group_id", Location: "query"}, {PublicName: "limit", WireName: "limit", Location: "query"}, {PublicName: "offset", WireName: "offset", Location: "query"}, {PublicName: "type", WireName: "type", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("b_create_b",
			mcplib.WithDescription("POST /b. Required: client_id, events, num_requests. Returns the new b."),
			mcplib.WithString("client_id", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("events", mcplib.Required(), mcplib.Description("")),
			mcplib.WithNumber("num_requests", mcplib.Required(), mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/b", []mcpParamBinding{{PublicName: "client_id", WireName: "client_id", Location: "body"}, {PublicName: "events", WireName: "events", Location: "body"}, {PublicName: "num_requests", WireName: "num_requests", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("default_create_endpoint",
			mcplib.WithDescription("POST /{id}. Required: id. Returns the new response."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id path segment")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("envelope_create_envelope",
			mcplib.WithDescription("POST /api/{id}/envelope/. Required: id. Optional: sentry_client, sentry_version. Returns the new envelope."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id path segment")),
			mcplib.WithString("sentry_client", mcplib.Description("")),
			mcplib.WithNumber("sentry_version", mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/{id}/envelope/", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "sentry_client", WireName: "sentry_client", Location: "query"}, {PublicName: "sentry_version", WireName: "sentry_version", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("f_get_f",
			mcplib.WithDescription("GET /f/{hash}/{hash}. Required: hash. Optional: Expires, Signature. Returns array of f."),
			mcplib.WithNumber("Expires", mcplib.Description("")),
			mcplib.WithString("Signature", mcplib.Description("")),
			mcplib.WithString("hash", mcplib.Required(), mcplib.Description("The hash path segment")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/f/{hash}/{hash}", []mcpParamBinding{{PublicName: "Expires", WireName: "Expires", Location: "query"}, {PublicName: "Signature", WireName: "Signature", Location: "query"}, {PublicName: "hash", WireName: "hash", Location: "path"}}, []string{"hash"}),
	)
	s.AddTool(
		mcplib.NewTool("groups_create_count_pending_invites",
			mcplib.WithDescription("POST /groups/{hash}/count-pending-invites. Required: hash. Returns the new count_pending_invites."),
			mcplib.WithString("hash", mcplib.Required(), mcplib.Description("The hash path segment")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/groups/{hash}/count-pending-invites", []mcpParamBinding{{PublicName: "hash", WireName: "hash", Location: "path"}}, []string{"hash"}),
	)
	s.AddTool(
		mcplib.NewTool("groups_get_admin_metrics",
			mcplib.WithDescription("GET /groups/{hash}/admin-metrics. Required: hash. Optional: amt, range. Returns the admin_metrics."),
			mcplib.WithString("amt", mcplib.Description("")),
			mcplib.WithString("hash", mcplib.Required(), mcplib.Description("The hash path segment")),
			mcplib.WithString("range", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/groups/{hash}/admin-metrics", []mcpParamBinding{{PublicName: "amt", WireName: "amt", Location: "query"}, {PublicName: "hash", WireName: "hash", Location: "path"}, {PublicName: "range", WireName: "range", Location: "query"}}, []string{"hash"}),
	)
	s.AddTool(
		mcplib.NewTool("groups_get_analytics_growth_overview_v2",
			mcplib.WithDescription("GET /groups/{hash}/analytics-growth-overview-v2. Required: hash. Returns the analytics_growth_overview_v2."),
			mcplib.WithString("hash", mcplib.Required(), mcplib.Description("The hash path segment")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/groups/{hash}/analytics-growth-overview-v2", []mcpParamBinding{{PublicName: "hash", WireName: "hash", Location: "path"}}, []string{"hash"}),
	)
	s.AddTool(
		mcplib.NewTool("groups_get_analytics_overview_v2",
			mcplib.WithDescription("GET /groups/{hash}/analytics-overview-v2. Required: hash. Returns the analytics_overview_v2."),
			mcplib.WithString("hash", mcplib.Required(), mcplib.Description("The hash path segment")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/groups/{hash}/analytics-overview-v2", []mcpParamBinding{{PublicName: "hash", WireName: "hash", Location: "path"}}, []string{"hash"}),
	)
	s.AddTool(
		mcplib.NewTool("groups_get_billing_payout_data",
			mcplib.WithDescription("GET /groups/{hash}/billing-payout-data. Required: hash. Optional: limit, offset. Returns the billing_payout_data."),
			mcplib.WithString("hash", mcplib.Required(), mcplib.Description("The hash path segment")),
			mcplib.WithNumber("limit", mcplib.Description("")),
			mcplib.WithNumber("offset", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/groups/{hash}/billing-payout-data", []mcpParamBinding{{PublicName: "hash", WireName: "hash", Location: "path"}, {PublicName: "limit", WireName: "limit", Location: "query"}, {PublicName: "offset", WireName: "offset", Location: "query"}}, []string{"hash"}),
	)
	s.AddTool(
		mcplib.NewTool("groups_get_discovery",
			mcplib.WithDescription("GET /groups/{hash}/discovery. Required: hash. Returns the discovery."),
			mcplib.WithString("hash", mcplib.Required(), mcplib.Description("The hash path segment")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/groups/{hash}/discovery", []mcpParamBinding{{PublicName: "hash", WireName: "hash", Location: "path"}}, []string{"hash"}),
	)
	s.AddTool(
		mcplib.NewTool("groups_get_member_course_permissions",
			mcplib.WithDescription("GET /groups/{hash}/member-course-permissions. Required: hash. Optional: member. Returns the member_course_permissions."),
			mcplib.WithString("hash", mcplib.Required(), mcplib.Description("The hash path segment")),
			mcplib.WithString("member", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/groups/{hash}/member-course-permissions", []mcpParamBinding{{PublicName: "hash", WireName: "hash", Location: "path"}, {PublicName: "member", WireName: "member", Location: "query"}}, []string{"hash"}),
	)
	s.AddTool(
		mcplib.NewTool("maps_list_sprite.json",
			mcplib.WithDescription("GET /maps/streets-v2/sprite.json. Optional: mtsid. Returns the sprite.json."),
			mcplib.WithString("mtsid", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/maps/streets-v2/sprite.json", []mcpParamBinding{{PublicName: "mtsid", WireName: "mtsid", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("maps_list_style.json",
			mcplib.WithDescription("GET /maps/streets-v2/style.json. Optional: mtsid. Returns the style.json."),
			mcplib.WithString("mtsid", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/maps/streets-v2/style.json", []mcpParamBinding{{PublicName: "mtsid", WireName: "mtsid", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("tiles_get_1.pbf",
			mcplib.WithDescription("GET /tiles/v3/{id}/{id}/1.pbf. Required: id. Optional: mtsid. Returns the 1.pbf."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id path segment")),
			mcplib.WithString("mtsid", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/tiles/v3/{id}/{id}/1.pbf", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "mtsid", WireName: "mtsid", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("tiles_get_2.pbf",
			mcplib.WithDescription("GET /tiles/v3/{id}/{id}/2.pbf. Required: id. Optional: mtsid. Returns the 2.pbf."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id path segment")),
			mcplib.WithString("mtsid", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/tiles/v3/{id}/{id}/2.pbf", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "mtsid", WireName: "mtsid", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("tiles_list_tiles.json",
			mcplib.WithDescription("GET /tiles/v3/tiles.json. Optional: mtsid. Returns the tiles.json."),
			mcplib.WithString("mtsid", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/tiles/v3/tiles.json", []mcpParamBinding{{PublicName: "mtsid", WireName: "mtsid", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("wait_list_wait",
			mcplib.WithDescription("GET /wait. Returns the wait."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/wait", []mcpParamBinding{}, []string{}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export SKOOL_API_KEY=<your-key>" +
					"\n      Run 'skool-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your API key." +
					"\n      Set it with: export SKOOL_API_KEY=<your-key>" +
					"\n      Run 'skool-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export SKOOL_API_KEY=<your-key>" +
					"\n      Run 'skool-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "skool-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 2)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "skool-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "skool",
		"description": "Discovered API spec for skool",
		"archetype":   "generic",
		"tool_count":  30,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion skool-pp-cli binary.",
		"auth": map[string]any{
			"type": "api_key",
			"env_vars": []map[string]any{
				{
					"name":        "SKOOL_API_KEY",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        ".deploy_status_henson.json",
				"description": "Operations on .deploy_status_henson.json",
				"endpoints":   []string{"list_.deploy_status_henson.json"},
			},
			{
				"name":        "017ae153ccc5",
				"description": "Operations on inputs",
				"endpoints":   []string{"create_mp_verify", "create_telemetry", "list_inputs"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "_next",
				"description": "Operations on members.json",
				"endpoints":   []string{"get_about.json", "get_calendar.json", "get_classroom.json", "get_leaderboards.json", "get_map.json", "get_members.json"},
				"searchable":  true,
			},
			{
				"name":        "affiliates",
				"description": "Operations on compensations",
				"endpoints":   []string{"list_compensations", "list_payout", "options_compensations"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "b",
				"description": "Operations on b",
				"endpoints":   []string{"create_b"},
				"searchable":  true,
			},
			{
				"name":        "default",
				"description": "Operations on default",
				"endpoints":   []string{"create_endpoint"},
			},
			{
				"name":        "envelope",
				"description": "Operations on envelope",
				"endpoints":   []string{"create_envelope"},
			},
			{
				"name":        "f",
				"description": "Operations on f",
				"endpoints":   []string{"get_f"},
				"searchable":  true,
			},
			{
				"name":        "groups",
				"description": "Operations on analytics-overview-v2",
				"endpoints":   []string{"create_count_pending_invites", "get_admin_metrics", "get_analytics_growth_overview_v2", "get_analytics_overview_v2", "get_billing_payout_data", "get_discovery", "get_member_course_permissions"},
				"searchable":  true,
			},
			{
				"name":        "maps",
				"description": "Operations on style.json",
				"endpoints":   []string{"list_sprite.json", "list_style.json"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "tiles",
				"description": "Operations on tiles.json",
				"endpoints":   []string{"get_1.pbf", "get_2.pbf", "list_tiles.json"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "wait",
				"description": "Operations on wait",
				"endpoints":   []string{"list_wait"},
				"syncable":    true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
