// Copyright 2026 robj1925. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newV017ae153ccc5Cmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "017ae153ccc5",
		Short: "Operations on inputs",
	}

	cmd.AddCommand(newV017ae153ccc5CreateMpVerifyCmd(flags))
	cmd.AddCommand(newV017ae153ccc5CreateTelemetryCmd(flags))
	cmd.AddCommand(newV017ae153ccc5ListInputsCmd(flags))
	return cmd
}
