// Copyright 2026 robj1925. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAffiliatesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "affiliates",
		Short: "Operations on compensations",
	}

	cmd.AddCommand(newAffiliatesListCompensationsCmd(flags))
	cmd.AddCommand(newAffiliatesListPayoutCmd(flags))
	return cmd
}
