// Copyright 2026 robj1925. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAffiliatesListPayoutCmd(flags *rootFlags) *cobra.Command {
	var flagCode string
	var flagCurrency string
	var flagLast30Days int
	var flagLifetime int
	var flagPayable int
	var flagPending int
	var flagSetupStatus string

	cmd := &cobra.Command{
		Use:         "list-payout",
		Short:       "GET /affiliates/payout",
		Example:     "  skool-pp-cli affiliates list-payout --code example-value --currency example-value --last-30-days 42 --lifetime 2026-01-15T09:00:00Z --payable 42 --pending 42 --setup-status example-value",
		Annotations: map[string]string{"pp:endpoint": "affiliates.list_payout", "pp:method": "GET", "pp:path": "/affiliates/payout", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("code") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "code")
			}
			if !cmd.Flags().Changed("currency") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "currency")
			}
			if !cmd.Flags().Changed("last-30-days") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "last-30-days")
			}
			if !cmd.Flags().Changed("lifetime") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "lifetime")
			}
			if !cmd.Flags().Changed("payable") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "payable")
			}
			if !cmd.Flags().Changed("pending") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "pending")
			}
			if !cmd.Flags().Changed("setup-status") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "setup-status")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/affiliates/payout"
			params := map[string]string{}
			if flagCode != "" {
				params["code"] = fmt.Sprintf("%v", flagCode)
			}
			if flagCurrency != "" {
				params["currency"] = fmt.Sprintf("%v", flagCurrency)
			}
			if flagLast30Days != 0 {
				params["last_30_days"] = fmt.Sprintf("%v", flagLast30Days)
			}
			if flagLifetime != 0 {
				params["lifetime"] = fmt.Sprintf("%v", flagLifetime)
			}
			if flagPayable != 0 {
				params["payable"] = fmt.Sprintf("%v", flagPayable)
			}
			if flagPending != 0 {
				params["pending"] = fmt.Sprintf("%v", flagPending)
			}
			if flagSetupStatus != "" {
				params["setup_status"] = fmt.Sprintf("%v", flagSetupStatus)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "affiliates", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagCode, "code", "", "")
	cmd.Flags().StringVar(&flagCurrency, "currency", "", "")
	cmd.Flags().IntVar(&flagLast30Days, "last-30-days", 0, "")
	cmd.Flags().IntVar(&flagLifetime, "lifetime", 0, "")
	cmd.Flags().IntVar(&flagPayable, "payable", 0, "")
	cmd.Flags().IntVar(&flagPending, "pending", 0, "")
	cmd.Flags().StringVar(&flagSetupStatus, "setup-status", "", "")

	return cmd
}
