// Copyright 2026 robj1925. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAffiliatesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "affiliates",
		Short: "Affiliate program and payouts",
		Long:  `Manage your Skool affiliate program, view compensations, and track payouts.`,
		Example: `  skool-pp-cli affiliates list_compensations
  skool-pp-cli affiliates list_payout`,
	}

	cmd.AddCommand(newAffiliatesListCompensationsCmd(flags))
	cmd.AddCommand(newAffiliatesListPayoutCmd(flags))
	return cmd
}
