// Copyright 2026 robj1925. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"os/exec"
	"regexp"
	"strings"

	"github.com/Robj1925/skool-pp-cli/internal/config"
	"github.com/spf13/cobra"
)

func newAuthCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "auth",
		Short: "Manage authentication for Skool",
		Long: `The auth command provides tools for managing your Skool session. 
Because Skool does not have a public API, the CLI uses your browser's 
session cookie to authenticate requests.`,
		Example: `  skool-pp-cli auth set-token "YOUR_COOKIE_STRING"
  skool-pp-cli auth status
  skool-pp-cli auth logout`,
	}

	cmd.AddCommand(newAuthStatusCmd(flags))
	cmd.AddCommand(newAuthSetTokenCmd(flags))
	cmd.AddCommand(newAuthLogoutCmd(flags))
	cmd.AddCommand(newAuthRefreshCmd(flags))
	cmd.AddCommand(newAuthLoginCmd(flags))
	cmd.AddCommand(newAuthImportHarCmd(flags))

	return cmd
}

func newAuthLoginCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:   "login",
		Short: "Automated login using a browser (requires Python + Playwright)",
		RunE: func(cmd *cobra.Command, args []string) error {
			fmt.Println("Attempting automated session refresh...")
			
			// Check if script exists
			scriptPath := "scripts/refresh_auth.js"
			if _, err := os.Stat(scriptPath); os.IsNotExist(err) {
				return fmt.Errorf("auth bridge script missing at %s", scriptPath)
			}

			// Run the node script
			// Use npx to ensure playwright is available/installed on the fly if needed
			fmt.Println("Starting Node.js automation...")
			var stderrBuf bytes.Buffer
			nodeCmd := exec.Command("node", scriptPath)
			nodeCmd.Stderr = &stderrBuf
			output, err := nodeCmd.Output()
			if err != nil {
				return fmt.Errorf("browser automation failed: %w\n\nNode Error Output:\n%s\n\nHint: Ensure you have playwright installed:\n  npm install playwright && npx playwright install chromium", err, stderrBuf.String())
			}

			// Find the COOKIE_RESULT in the output
			re := regexp.MustCompile(`COOKIE_RESULT=(.*)`)
			matches := re.FindStringSubmatch(string(output))
			if len(matches) < 2 {
				return fmt.Errorf("could not find cookie result in automation output")
			}

			cookieString := strings.TrimSpace(matches[1])
			
			// Save the token
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return err
			}
			cfg.AuthHeaderVal = ""
			if err := cfg.SaveCredential(cookieString); err != nil {
				return err
			}

			fmt.Println("Success! Stored fresh session cookies.")
			return nil
		},
	}
}

func newAuthRefreshCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:   "refresh",
		Short: "Get step-by-step instructions for refreshing your Skool session",
		RunE: func(cmd *cobra.Command, args []string) error {
			msg := `
SKOOL AUTH REFRESH RUNBOOK
==========================

Because Skool does not offer a public API, this CLI relies on your active browser session cookie. If your commands start failing with 401 Unauthorized or 403 Forbidden, your session has likely expired.

Follow these steps to recapture your session:

1. Open an incognito/private browser window.
2. Go to skool.com and log in with your credentials.
3. Open Developer Tools (F12 or Right Click -> Inspect).
4. Go to the 'Network' tab.
5. Click on any community or page to trigger some network requests.
6. Look for a request to an endpoint like 'members.json' or 'analytics'.
7. Click the request, go to the 'Headers' tab, and find the 'Request Headers' section.
8. Look for the 'cookie:' header. Right-click and copy the entire string.
9. Run this command to save your new cookie:
   
   skool-pp-cli auth set-token "YOUR_COPIED_COOKIE_STRING"

Alternatively, to capture all endpoints via a new HAR file:
1. Export the Network tab as a .har file.
2. Replace your local skool-capture.har file.
3. Use the 'har update' runbook to re-extract endpoints if the Skool API changed.
`
			fmt.Fprintln(cmd.OutOrStdout(), msg)
			return nil
		},
	}
}

func newAuthStatusCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "status",
		Short:   "Show authentication status",
		Example: "  skool-pp-cli auth status",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			w := cmd.OutOrStdout()
			header := cfg.AuthHeader()
			authed := header != ""
			// JSON envelope: {authenticated, source, config}. When not
			// authenticated, write the envelope first then return authErr
			// so exit code carries the auth-failure signal.
			if flags.asJSON {
				out := map[string]any{
					"authenticated": authed,
					"source":        cfg.AuthSource,
					"config":        cfg.Path,
				}
				if printErr := printJSONFiltered(w, out, flags); printErr != nil {
					return printErr
				}
				if !authed {
					return authErr(fmt.Errorf("no credentials configured"))
				}
				return nil
			}
			if !authed {
				fmt.Fprintln(w, red("Not authenticated"))
				fmt.Fprintln(w, "")
				fmt.Fprintln(w, "Set your token:")
				fmt.Fprintln(w, "  export SKOOL_API_KEY=\"your-token-here\"")
				fmt.Fprintf(w, "  skool-pp-cli auth set-token <token>\n")
				return authErr(fmt.Errorf("no credentials configured"))
			}

			fmt.Fprintln(w, green("Authenticated"))
			fmt.Fprintf(w, "  Source: %s\n", cfg.AuthSource)
			fmt.Fprintf(w, "  Config: %s\n", cfg.Path)
			return nil
		},
	}
}

func newAuthSetTokenCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "set-token <token>",
		Short:   "Save an API token to the config file",
		Example: "  skool-pp-cli auth set-token YOUR_TOKEN_HERE",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			// Clear any legacy auth_header so AuthHeader() falls through to
			// the newly-saved credential. Without this, a pre-existing
			// auth_header value (common after regenerate) shadows the saved
			// token and set-token silently has no effect. Silent clear (no
			// log line): a masked-tail variant could leak token bytes through
			// scripted dogfood that captures stderr.
			cfg.AuthHeaderVal = ""
			// api_key auth: AuthHeader() reads the env-var-derived field, not
			// AccessToken. Writing the token to AccessToken via SaveTokens
			// would persist the bytes but leave doctor reporting "not
			// configured" — the slot the header builder consults stays empty.
			if err := cfg.SaveCredential(args[0]); err != nil {
				return configErr(fmt.Errorf("saving token: %w", err))
			}

			// JSON envelope: {saved, config_path}.
			if flags.asJSON {
				return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
					"saved":       true,
					"config_path": cfg.Path,
				}, flags)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Token saved to %s\n", cfg.Path)
			return nil
		},
	}
}

func newAuthLogoutCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "logout",
		Short:   "Clear stored credentials",
		Example: "  skool-pp-cli auth logout",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			if err := cfg.ClearTokens(); err != nil {
				return configErr(fmt.Errorf("clearing tokens: %w", err))
			}

			// Identify which (if any) auth env var is still exported so the
			// JSON envelope and the human prose can both surface it.
			envStillSet := ""
			if envStillSet == "" && os.Getenv("SKOOL_API_KEY") != "" {
				envStillSet = "SKOOL_API_KEY"
			}

			// JSON envelope: {cleared: true, note?: "<env_var> env var is still set"}.
			if flags.asJSON {
				out := map[string]any{"cleared": true}
				if envStillSet != "" {
					out["note"] = envStillSet + " env var is still set"
				}
				return printJSONFiltered(cmd.OutOrStdout(), out, flags)
			}

			if envStillSet != "" {
				fmt.Fprintf(cmd.OutOrStdout(), "Config cleared. Note: %s env var is still set.\n", envStillSet)
				return nil
			}
			fmt.Fprintln(cmd.OutOrStdout(), "Logged out. Credentials cleared.")
			return nil
		},
	}
}

func newAuthImportHarCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:   "import-har <path>",
		Short: "Extract session cookies from a browser HAR export",
		Long: `Extracts the 'cookie' header from a .har file exported from your browser's 
Network tab. This is a reliable alternative to automated login when 
browser automation is blocked or unstable.

How to get a HAR file:
1. Open skool.com in your browser and log in.
2. Open Developer Tools (F12) -> Network tab.
3. Chrome only: Click Gear Icon -> Check "Allow to generate HAR with sensitive data".
4. CRITICAL: Refresh the page while the Network tab is open.
5. Export the HAR (choose "with sensitive data" in Chrome).
6. Run: skool-pp-cli auth import-har path/to/export.har`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := args[0]
			data, err := os.ReadFile(path)
			if err != nil {
				return fmt.Errorf("reading HAR file: %w", err)
			}

			// Simple HAR structure traversal
			var har struct {
				Log struct {
					Entries []struct {
						Request struct {
							URL     string `json:"url"`
							Headers []struct {
								Name  string `json:"name"`
								Value string `json:"value"`
							} `json:"headers"`
						} `json:"request"`
					} `json:"entries"`
				} `json:"log"`
			}

			if err := json.Unmarshal(data, &har); err != nil {
				return fmt.Errorf("parsing HAR JSON: %w", err)
			}

			var bestCookie string
			var domainsFound []string
			for _, entry := range har.Log.Entries {
				u, err := url.Parse(entry.Request.URL)
				if err != nil {
					continue
				}
				
				isSkool := strings.Contains(u.Host, "skool.com")
				if isSkool {
					for _, header := range entry.Request.Headers {
						if strings.ToLower(header.Name) == "cookie" {
							// Look for cookies containing auth material
							if strings.Contains(header.Value, "auth_token") || strings.Contains(header.Value, "aws-waf-token") {
								bestCookie = header.Value
								break
							}
						}
					}
				} else {
					domainsFound = append(domainsFound, u.Host)
				}
				
				if bestCookie != "" {
					break
				}
			}

			if bestCookie == "" {
				msg := "no session cookies found in HAR file.\n"
				if len(har.Log.Entries) == 0 {
					msg += "The HAR file appears to be empty (0 entries)."
				} else {
					msg += fmt.Sprintf("Found %d requests, but none contained Skool authentication material.\n", len(har.Log.Entries))
					msg += "Ensure you REFRESH the page while the Network tab is open before exporting."
				}
				return fmt.Errorf(msg)
			}

			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return err
			}
			cfg.AuthHeaderVal = ""
			if err := cfg.SaveCredential(bestCookie); err != nil {
				return err
			}

			fmt.Printf("Success! Imported session cookies from %s\n", path)
			return nil
		},
	}
}
