// Copyright 2026 robj1925. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGroupsGetAdminMetricsCmd(flags *rootFlags) *cobra.Command {
	var flagAmt string
	var flagRange string

	cmd := &cobra.Command{
		Use:         "get-admin-metrics <hash>",
		Short:       "GET /groups/{hash}/admin-metrics",
		Example:     "  skool-pp-cli groups get-admin-metrics example-value",
		Annotations: map[string]string{"pp:endpoint": "groups.get_admin_metrics", "pp:method": "GET", "pp:path": "/groups/{hash}/admin-metrics", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/groups/{hash}/admin-metrics"
			if len(args) < 2 {
				return usageErr(fmt.Errorf("hash is required\nUsage: %s <%s>", cmd.CommandPath(), "hash"))
			}
			path = replacePathParam(path, "hash", args[1])
			params := map[string]string{}
			if flagAmt != "" {
				params["amt"] = fmt.Sprintf("%v", flagAmt)
			}
			if flagRange != "" {
				params["range"] = fmt.Sprintf("%v", flagRange)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "groups", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagAmt, "amt", "", "")
	cmd.Flags().StringVar(&flagRange, "range", "", "")

	return cmd
}
