// Copyright 2026 robj1925. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGroupsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "groups",
		Short: "Community analytics and group management",
		Long: `Manage your Skool groups and access deep analytics for each group. 
This includes admin metrics, growth overviews, and billing data.`,
		Example: `  skool-pp-cli groups get_admin_metrics --hash <group-hash>
  skool-pp-cli groups get_analytics_overview_v2 --hash <group-hash>`,
	}

	cmd.AddCommand(newGroupsCreateCountPendingInvitesCmd(flags))
	cmd.AddCommand(newGroupsGetAdminMetricsCmd(flags))
	cmd.AddCommand(newGroupsGetAnalyticsGrowthOverviewV2Cmd(flags))
	cmd.AddCommand(newGroupsGetAnalyticsOverviewV2Cmd(flags))
	cmd.AddCommand(newGroupsGetBillingPayoutDataCmd(flags))
	cmd.AddCommand(newGroupsGetDiscoveryCmd(flags))
	cmd.AddCommand(newGroupsGetMemberCoursePermissionsCmd(flags))
	return cmd
}
