// Copyright 2026 robj1925. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMapsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "maps",
		Short: "Map styles and assets",
		Long:  `Access map styles, sprites, and other assets used for community map features.`,
	}

	cmd.AddCommand(newMapsListSpriteJsonCmd(flags))
	cmd.AddCommand(newMapsListStyleJsonCmd(flags))
	return cmd
}
