// Copyright 2026 robj1925. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newNextCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "next",
		Short: "Core community data (members, classroom, calendar)",
		Long: `Access core community data endpoints used by the Skool frontend. 
This includes member lists, classroom content, calendar events, and leaderboards.`,
		Example: `  skool-pp-cli next get_members.json --id <group-id>
  skool-pp-cli next get_classroom.json --id <group-id>`,
	}

	cmd.AddCommand(newNextGetAboutJsonCmd(flags))
	cmd.AddCommand(newNextGetCalendarJsonCmd(flags))
	cmd.AddCommand(newNextGetClassroomJsonCmd(flags))
	cmd.AddCommand(newNextGetLeaderboardsJsonCmd(flags))
	cmd.AddCommand(newNextGetMapJsonCmd(flags))
	cmd.AddCommand(newNextGetMembersJsonCmd(flags))
	return cmd
}
