// Copyright 2026 robj1925. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newDeployStatusHensonJsonPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagCanaryPercentage int
	var flagDeployedRevisions string

	cmd := &cobra.Command{
		Use:         ".deploy-status-henson.json",
		Short:       "GET /v3/.deploy_status_henson.json",
		Long:        "Shortcut for '.deploy_status_henson.json list_.deploy_status_henson.json'. GET /v3/.deploy_status_henson.json",
		Example:     "  skool-pp-cli .deploy-status-henson.json --canary-percentage 42 --deployed-revisions example-value",
		Annotations: map[string]string{"pp:endpoint": ".deploy_status_henson.json.list_.deploy_status_henson.json", "pp:method": "GET", "pp:path": "/v3/.deploy_status_henson.json", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("canary-percentage") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "canary-percentage")
			}
			if !cmd.Flags().Changed("deployed-revisions") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "deployed-revisions")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v3/.deploy_status_henson.json"
			params := map[string]string{}
			if flagCanaryPercentage != 0 {
				params["canaryPercentage"] = fmt.Sprintf("%v", flagCanaryPercentage)
			}
			if flagDeployedRevisions != "" {
				params["deployedRevisions"] = fmt.Sprintf("%v", flagDeployedRevisions)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, ".deploy_status_henson.json", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagCanaryPercentage, "canary-percentage", 0, "")
	cmd.Flags().StringVar(&flagDeployedRevisions, "deployed-revisions", "", "")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
