// Copyright 2026 robj1925. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
	"text/tabwriter"
	"time"

	"github.com/Robj1925/skool-pp-cli/internal/client"
	"github.com/Robj1925/skool-pp-cli/internal/config"
	"github.com/spf13/cobra"
)

var version = "1.0.0"

type rootFlags struct {
	asJSON        bool
	compact       bool
	csv           bool
	plain         bool
	quiet         bool
	dryRun        bool
	noCache       bool
	noInput       bool
	idempotent    bool
	yes           bool
	agent         bool
	selectFields  string
	configPath    string
	profileName   string
	deliverSpec   string
	timeout       time.Duration
	rateLimit     float64
	dataSource    string
	freshnessMeta any

	// deliverBuf captures command output when --deliver is set to a
	// non-stdout sink. Flushed to the sink after Execute returns.
	deliverBuf  *bytes.Buffer
	deliverSink DeliverSink
}

// RootCmd returns the Cobra command tree without executing it. The MCP server
// uses this to mirror every user-facing command as an agent tool.
func RootCmd() *cobra.Command {
	var flags rootFlags
	return newRootCmd(&flags)
}

// Execute runs the CLI in non-interactive mode: never prompts, all values via flags or stdin.
func Execute() error {
	var flags rootFlags
	rootCmd := newRootCmd(&flags)

	err := rootCmd.Execute()
	if err != nil {
		msg := err.Error()
		handled := false
		if strings.Contains(msg, "unknown flag") {
			if idx := strings.Index(msg, "unknown flag: "); idx >= 0 {
				flagStr := strings.TrimSpace(msg[idx+len("unknown flag: "):])
				if suggestion := suggestFlag(flagStr, rootCmd); suggestion != "" {
					fmt.Fprintf(os.Stderr, "Error: %v\nhint: did you mean --%s?\n", err, suggestion)
					handled = true
				}
			}
		} else if strings.Contains(msg, "unknown command") {
			if idx := strings.Index(msg, "unknown command"); idx >= 0 {
				parts := strings.Split(msg, "\"")
				if len(parts) >= 2 {
					unknownCmd := parts[1]
					if suggestion := suggestCommand(unknownCmd, rootCmd); suggestion != "" {
						fmt.Fprintf(os.Stderr, "Error: %v\nhint: did you mean '%s'?\n", err, suggestion)
						handled = true
					}
				}
			}
		}
		if !handled {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		}
	}
	if err == nil && flags.deliverBuf != nil {
		if derr := Deliver(flags.deliverSink, flags.deliverBuf.Bytes(), flags.compact); derr != nil {
			fmt.Fprintf(os.Stderr, "warning: deliver to %s:%s failed: %v\n", flags.deliverSink.Scheme, flags.deliverSink.Target, derr)
			return derr
		}
	}
	return err
}

func newRootCmd(flags *rootFlags) *cobra.Command {
	rootCmd := &cobra.Command{
		Use:   "skool-pp-cli",
		Short: "High-performance CLI for Skool community management and analytics",
		Long: `Skool Community CLI (skool-pp-cli)

A powerful command-line interface for Skool community owners and power users. 
It provides deep domain analytics, behavioral insights, and automated management 
capabilities that go beyond the standard browser interface.

Key Capabilities:
  - Full Data Sync: Download your community data to a local SQLite database for offline analysis.
  - Domain Analytics (Rung 4): Identify orphaned members, stale activity, and top contributors.
  - Behavioral Insights (Rung 5): Predict churn risk and track member growth velocity.
  - Chat & Messaging: Send and receive direct messages from the terminal.
  - Content Management: Create posts and manage community content programmatically.
  - Search: Instant full-text search across your entire community data.

Common Workflows:
  1. Authenticate:   skool-pp-cli auth set-token "YOUR_COOKIE_STRING"
  2. Verify:         skool-pp-cli doctor
  3. Sync Data:      skool-pp-cli sync
  4. Run Analytics:  skool-pp-cli analytics-domain orphans

Add --agent to any command for JSON output + non-interactive mode.`,
		SilenceUsage:  true,
		SilenceErrors: true,
		Version:       version,
	}
	rootCmd.SetVersionTemplate("skool-pp-cli {{ .Version }}\n")

	rootCmd.PersistentFlags().BoolVar(&flags.asJSON, "json", false, "Output as JSON")
	rootCmd.PersistentFlags().BoolVar(&flags.compact, "compact", false, "Return only key fields (id, name, status, timestamps) for minimal token usage")
	rootCmd.PersistentFlags().BoolVar(&flags.csv, "csv", false, "Output as CSV (table and array responses)")
	rootCmd.PersistentFlags().BoolVar(&flags.plain, "plain", false, "Output as plain tab-separated text")
	rootCmd.PersistentFlags().BoolVar(&flags.quiet, "quiet", false, "Bare output, one value per line")
	rootCmd.PersistentFlags().StringVar(&flags.configPath, "config", "", "Config file path")
	rootCmd.PersistentFlags().DurationVar(&flags.timeout, "timeout", 30*time.Second, "Request timeout")
	rootCmd.PersistentFlags().BoolVar(&flags.dryRun, "dry-run", false, "Show request without sending")
	rootCmd.PersistentFlags().BoolVar(&flags.noCache, "no-cache", false, "Bypass response cache")
	rootCmd.PersistentFlags().BoolVar(&flags.noInput, "no-input", false, "Disable all interactive prompts (for CI/agents)")
	rootCmd.PersistentFlags().BoolVar(&flags.idempotent, "idempotent", false, "Treat already-existing create results as a successful no-op")
	rootCmd.PersistentFlags().StringVar(&flags.selectFields, "select", "", "Comma-separated fields to include in output (e.g. --select id,name,status)")
	rootCmd.PersistentFlags().BoolVar(&flags.yes, "yes", false, "Skip confirmation prompts (for agents and scripts)")
	rootCmd.PersistentFlags().BoolVar(&noColor, "no-color", false, "Disable colored output")
	rootCmd.PersistentFlags().BoolVar(&humanFriendly, "human-friendly", false, "Enable colored output and rich formatting")
	rootCmd.PersistentFlags().BoolVar(&flags.agent, "agent", false, "Set all agent-friendly defaults (--json --compact --no-input --no-color --yes)")
	rootCmd.PersistentFlags().StringVar(&flags.dataSource, "data-source", "auto", "Data source for read commands: auto (live with local fallback), live (API only), local (synced data only)")
	rootCmd.PersistentFlags().StringVar(&flags.profileName, "profile", "", "Apply values from a saved profile (see 'skool-pp-cli profile list')")
	rootCmd.PersistentFlags().StringVar(&flags.deliverSpec, "deliver", "", "Route output to a sink: stdout (default), file:<path>, webhook:<url>")
	rootCmd.PersistentFlags().Float64Var(&flags.rateLimit, "rate-limit", 2, "Max requests per second (0 to disable, default 2 for sniffed APIs)")

	rootCmd.PersistentPreRunE = func(cmd *cobra.Command, args []string) error {
		if flags.deliverSpec != "" {
			sink, err := ParseDeliverSink(flags.deliverSpec)
			if err != nil {
				return err
			}
			flags.deliverSink = sink
			if sink.Scheme != "stdout" && sink.Scheme != "" {
				flags.deliverBuf = &bytes.Buffer{}
				cmd.SetOut(io.MultiWriter(os.Stdout, flags.deliverBuf))
			}
		}
		if flags.profileName != "" {
			profile, err := GetProfile(flags.profileName)
			if err != nil {
				return err
			}
			if profile == nil {
				available := ListProfileNames()
				if len(available) == 0 {
					return fmt.Errorf("profile %q not found (no profiles saved yet; run '%s profile save <name> --<flag> <value>')", flags.profileName, cmd.Root().Name())
				}
				return fmt.Errorf("profile %q not found; available: %s", flags.profileName, strings.Join(available, ", "))
			}
			if err := ApplyProfileToFlags(cmd, profile); err != nil {
				return err
			}
		}
		if flags.agent {
			if !cmd.Flags().Changed("json") {
				flags.asJSON = true
			}
			if !cmd.Flags().Changed("compact") {
				flags.compact = true
			}
			if !cmd.Flags().Changed("no-input") {
				flags.noInput = true
			}
			if !cmd.Flags().Changed("yes") {
				flags.yes = true
			}
			if !cmd.Flags().Changed("no-color") {
				noColor = true
			}
		}
		switch flags.dataSource {
		case "auto", "live", "local":
			// valid
		default:
			return fmt.Errorf("invalid --data-source value %q: must be auto, live, or local", flags.dataSource)
		}
		return nil
	}
	rootCmd.AddCommand(newInstallCmd())
	rootCmd.AddCommand(newV017ae153ccc5Cmd(flags))
	rootCmd.AddCommand(newNextCmd(flags))
	rootCmd.AddCommand(newAffiliatesCmd(flags))
	rootCmd.AddCommand(newGroupsCmd(flags))
	rootCmd.AddCommand(newPostsCmd(flags))
	rootCmd.AddCommand(newChannelsCmd(flags))
	rootCmd.AddCommand(newMapsCmd(flags))
	rootCmd.AddCommand(newTilesCmd(flags))
	rootCmd.AddCommand(newDoctorCmd(flags))
	rootCmd.AddCommand(newAuthCmd(flags))
	rootCmd.AddCommand(newAgentContextCmd(rootCmd))
	rootCmd.AddCommand(newProfileCmd(flags))
	rootCmd.AddCommand(newFeedbackCmd(flags))
	rootCmd.AddCommand(newWhichCmd(flags))
	rootCmd.AddCommand(newExportCmd(flags))
	rootCmd.AddCommand(newImportCmd(flags))
	rootCmd.AddCommand(newSearchCmd(flags))
	rootCmd.AddCommand(newSyncCmd(flags))
	rootCmd.AddCommand(newWorkflowCmd(flags))
	rootCmd.AddCommand(newAPICmd(flags))
	rootCmd.AddCommand(newDeployStatusHensonJsonPromotedCmd(flags))
	rootCmd.AddCommand(newBPromotedCmd(flags))
	rootCmd.AddCommand(newDefaultPromotedCmd(flags))
	rootCmd.AddCommand(newEnvelopePromotedCmd(flags))
	rootCmd.AddCommand(newFPromotedCmd(flags))
	rootCmd.AddCommand(newWaitPromotedCmd(flags))
	rootCmd.AddCommand(newVersionCliCmd())
	rootCmd.AddCommand(newInsightsCmd(flags))
	rootCmd.AddCommand(newAnalyticsDomainCmd(flags))

	return rootCmd
}

// suggestCommand searches the command tree for the closest match to an unknown command.
func suggestCommand(unknown string, cmd *cobra.Command) string {
	best := ""
	bestScore := 0.0

	for _, sub := range cmd.Commands() {
		score := stringSimilarity(unknown, sub.Name())
		if score > bestScore && score > 0.6 {
			best = sub.Name()
			bestScore = score
		}
		for _, alias := range sub.Aliases {
			score := stringSimilarity(unknown, alias)
			if score > bestScore && score > 0.6 {
				best = sub.Name()
				bestScore = score
			}
		}
	}
	return best
}

func stringSimilarity(s1, s2 string) float64 {
	if s1 == s2 {
		return 1.0
	}
	if len(s1) == 0 || len(s2) == 0 {
		return 0.0
	}
	// Simple Levenshtein-based similarity
	distance := levenshtein(s1, s2)
	maxLen := len(s1)
	if len(s2) > maxLen {
		maxLen = len(s2)
	}
	return 1.0 - float64(distance)/float64(maxLen)
}

func levenshtein(s1, s2 string) int {
	d := make([][]int, len(s1)+1)
	for i := range d {
		d[i] = make([]int, len(s2)+1)
		d[i][0] = i
	}
	for j := range d[0] {
		d[0][j] = j
	}
	for i := 1; i <= len(s1); i++ {
		for j := 1; j <= len(s2); j++ {
			cost := 1
			if s1[i-1] == s2[j-1] {
				cost = 0
			}
			d[i][j] = min(d[i-1][j]+1, min(d[i][j-1]+1, d[i-1][j-1]+cost))
		}
	}
	return d[len(s1)][len(s2)]
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func ExitCode(err error) int {
	var codeErr *cliError
	if As(err, &codeErr) {
		return codeErr.code
	}
	return 1
}

func (f *rootFlags) newClient() (*client.Client, error) {
	cfg, err := config.Load(f.configPath)
	if err != nil {
		return nil, configErr(err)
	}
	c := client.New(cfg, f.timeout, f.rateLimit)
	c.DryRun = f.dryRun
	c.NoCache = f.noCache
	return c, nil
}

func (f *rootFlags) printJSON(w *cobra.Command, v any) error {
	enc := json.NewEncoder(w.OutOrStdout())
	enc.SetIndent("", "  ")
	return enc.Encode(v)
}

func (f *rootFlags) printTable(w *cobra.Command, headers []string, rows [][]string) error {
	if f.asJSON {
		return fmt.Errorf("use printJSON for JSON output")
	}
	tw := tabwriter.NewWriter(w.OutOrStdout(), 2, 4, 2, ' ', 0)
	header := ""
	for i, h := range headers {
		if i > 0 {
			header += "\t"
		}
		header += h
	}
	fmt.Fprintln(tw, header)
	for _, row := range rows {
		line := ""
		for i, cell := range row {
			if i > 0 {
				line += "\t"
			}
			line += cell
		}
		fmt.Fprintln(tw, line)
	}
	return tw.Flush()
}

func newVersionCliCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "version",
		Short: "Print version",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Printf("skool-pp-cli %s\n", version)
		},
	}
}
