// Copyright 2026 robj1925. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTilesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tiles",
		Short: "Operations on tiles.json",
	}

	cmd.AddCommand(newTilesGet1PbfCmd(flags))
	cmd.AddCommand(newTilesGet2PbfCmd(flags))
	cmd.AddCommand(newTilesListTilesJsonCmd(flags))
	return cmd
}
